services:
  mongodb:
    image: mongo:7.0
    container_name: parts-manager-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=parts_manager

volumes:
  mongo_data:
