spring:
  application:
    name: part-manager-backend


  mongodb:
    uri: ${MONGODB_URI:mongodb://localhost:27017/part_manager}

  ai:
    google:
      genai:
        api-key: ${AI_API_KEY:mock-key}
    openai:
      api-key: ${AI_API_KEY:mock-key}

  main:
    allow-bean-definition-overriding: on

server:
  port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
