spring:
  application:
    name: part-manager-backend

  mongodb:
    uri: ${MONGODB_URI:mongodb://localhost:27017/parts_manager}

  ai:
    google:
      genai:
        api-key: ${AI_API_KEY:mock-key}
        chat:
          options:
            model: gemini-3.6-flash

server:
  port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
